---
- type: replace
  path: /releases/name=loggregator?
  value:
    name: loggregator
    version: '103.0'
    url: "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=103.0"
    sha1: 41fe210afef030a9bae37795fdd7c5e5ca779ea3

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value: &metron_agent_config
    name: metron_agent
    release: loggregator
    properties:
      metron_agent:
        deployment: ((deployment-name))
      loggregator:
        tls:
          ca_cert: ((loggregator-tls-ca-cert))
          metron:
            cert: ((loggregator-tls-metron-cert))
            key: ((loggregator-tls-metron-key))

- type: replace
  path: /instance_groups/name=haproxy/jobs/-
  value: *metron_agent_config
